---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: addons.k3s.cattle.io
spec:
  group: k3s.cattle.io
  names:
    kind: Addon
    listKind: AddonList
    plural: addons
    singular: addon
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.source
      name: Source
      type: string
    - jsonPath: .spec.checksum
      name: Checksum
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: |-
          Addon is used to track application of a manifest file on disk. It mostly exists so that the wrangler DesiredSet
          Apply controller has an object to track as the owner, and ensure that all created resources are tracked when the
          manifest is modified or removed.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec provides information about the on-disk manifest backing
              this resource.
            properties:
              checksum:
                description: Checksum is the SHA256 checksum of the most recently
                  successfully applied manifest file.
                type: string
              source:
                description: Source is the Path on disk to the manifest file that
                  this Addon tracks.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
