name: Build
env:
  OEM: ${{ inputs.OEM }}
on: 
  workflow_call:
   inputs:
    arch:
      type: string
      description: 'Architecture to build'
      default: 'ubuntu-latest'
    upload-image:
      type: boolean
      required: false
      default: false
  workflow_dispatch:
   inputs:
    OEM:
      default: vip
      description: Meta
      required: true
      type: string

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 20
    env:
      BIN_EXT: ${{ inputs.os == 'windows' && '.exe' || '' }}
      ARCH_EXT: ${{ inputs.os == 'windows' && '-windows' || format('-{0}', inputs.arch) }}
      GOOS: ${{ inputs.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build binary
      run: |
        DOCKER_BUILDKIT=1 SKIP_IMAGE=1 SKIP_AIRGAP=1 SKIP_IMAGE=1 SKIP_VALIDATE=1 GOCOVER=1 make
        sha256sum dist/artifacts/k3s | sed 's|dist/artifacts/||' > dist/artifacts/k3s.sha256sum
    - name: "Upload binary"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.OEM }}-amd64
        path: dist/artifacts/k3s*
  arm64:
    name: Build-${{ inputs.OEM }}
    runs-on: ubuntu-24.04-arm
    if: always()
    timeout-minutes: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build binary
      run: |
        DOCKER_BUILDKIT=1 SKIP_IMAGE=1 SKIP_AIRGAP=1 SKIP_IMAGE=1 SKIP_VALIDATE=1 GOCOVER=1 make
        sha256sum dist/artifacts/k3s-arm64 | sed 's|dist/artifacts/||' > dist/artifacts/k3s.sha256sum
    - name: "Upload binary"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.OEM }}-arm64
        path: dist/artifacts/k3s*
